# Generated by Django 5.2.15 on 2026-08-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('concern', models.CharField(choices=[('aligners', 'Aligners'), ('whitening', 'Teeth Whitening'), ('implants', 'Dental Implants'), ('cleaning', 'Cleaning / Scaling'), ('general', 'Tooth Pain / General Consultation'), ('other', 'Other')], max_length=30)),
                ('other_concern', models.TextField(blank=True, null=True)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.CharField(choices=[('09:30', '09:30 AM'), ('10:00', '10:00 AM'), ('10:30', '10:30 AM'), ('11:00', '11:00 AM'), ('11:30', '11:30 AM'), ('12:00', '12:00 PM'), ('12:30', '12:30 PM'), ('13:00', '01:00 PM'), ('13:30', '01:30 PM'), ('14:00', '02:00 PM'), ('14:30', '02:30 PM'), ('15:00', '03:00 PM'), ('15:30', '03:30 PM'), ('16:00', '04:00 PM'), ('16:30', '04:30 PM'), ('17:00', '05:00 PM'), ('17:30', '05:30 PM'), ('18:00', '06:00 PM'), ('18:30', '06:30 PM'), ('19:00', '07:00 PM'), ('19:30', '07:30 PM')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['appointment_date', 'appointment_time'],
                'constraints': [models.UniqueConstraint(fields=('appointment_date', 'appointment_time'), name='unique_appointment_slot')],
            },
        ),
    ]
